version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: deep-town-event-bot-db
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: on-failure

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deep-town-event-bot
    volumes:
      - bot_data:/bot
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /bot
          ignore:
            - venv/
            - requirements.txt
        - action: rebuild
          path: requirements.txt
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 30s

volumes:
  postgres_data:
  bot_data:
