version: '3.8'

services:
    db:
        image: postgres:latest
        container_name: deep-town-event-bot-db
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        restart: on-failure
    bot:
        build: .
        container_name: deep-town-event-bot
        # volumes:
        #    -   .:/bot/
        depends_on:
            - db
        restart: on-failure

volumes:
    postgres_data:
