version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deep-town-event-bot
    volumes:
      - bot_data:/bot
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /bot
          ignore:
            - venv/
            - requirements.txt
            - Dockerfile
            - docker-compose_standalone.yml
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: docker-compose_standalone.yml
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 30s

volumes:
  bot_data:
