version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deep-town-event-bot
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /bot
          ignore:
            - venv/
            - requirements.txt
        - action: rebuild
          path: requirements.txt
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 30s
