# Ids should be unset by setting them to -1 but some may be required

[base]
discord_api_key = "<env>" # "<env>" means that this setting will be loaded from environmental variable with key "base_discord_api_key"
command_prefix = "!"
required_permissions = 274878426176
developer_ids = []
sync_discord = true
command_sync_debug = false
master_discord_guild_ids = [] # Used for registering owner only commands to master only guilds

# If true warning and error logs will also be logged in file discord.log
log_to_file = false
log_channel_id = -1

# Duration of error and success messages
error_duration = 30
success_duration = 30

# Connection string to database with specified engine
# This address is for usage with docker deployment
database_connect_string = "postgresql://postgres:postgres@db:5432/postgres" # Example for testing: "sqlite://database.db" For docker workflow: "postgresql://postgres:postgres@db:5432/postgres"

default_loaded_extensions = ["common", "dt_dynamic_data_manager", "dt_report_announcer", "dt_blacklist", "dt_event_item_lottery", "dt_guilds", "dt_users", "dt_events", "dt_statistics", "better_message_links", "auto_help"]

[presence]
status_messages = ["Serving {guilds} discord servers with {users} users", "Monitoring Deep Town Events", "Monitoring {total_dt_guilds} Deep Town guilds and {total_dt_users} members", "Find every feature of this bot by using `/help` command", "Deep Town have {dt_guilds} active guilds with {dt_users} active members", "Invite this bot to your guild by using `/common invite` command"]
cycle_interval_s = 120

[data_manager]
ignore_empty_guilds = true

clean_none_existing_guilds = true
cleanup_rate_days = 7

periodically_pull_data = true
data_pull_rate_hours = 6
pull_data_startup_delay_seconds = 60

inactive_guild_data_pull_rate_hours = 168 # Disable by setting it to value 0 or less
activity_days_threshold = 15

[event_tracker]
tracker_limit_per_guild = 5

# Dont change if you dont know what you are doing
event_start_day = 3 # 0 - monday, 6 - sunday
event_start_hour = 8
event_start_minute = 0

# Dont change if you dont know what you are doing
event_length_days = 4 # 0 - monday, 6 - sunday
event_length_hours = 0
event_length_minutes = 0

event_announce_offset_minutes = 15

[lotteries]
clean_old_lotteries_period_days = 10
clean_lotteries_closed_for_more_than_days = 60

[blacklist]
report_channel_id = -1

[questions_and_answers]
score_limit = 60 # From 0 to 100 - larger number the less sensitive it is
